# Generated by Django 4.0.6 on 2022-07-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
